import { PrismaAuthRepository } from "./adapters/PrismaAuthRepository";
import { JoseTokenService } from "./adapters/JoseTokenService";
import { LoginWithPasswordUseCase } from "../application/LoginWithPasswordUseCase";
import { GenerateLoginChallengeUseCase } from "../application/GenerateLoginChallengeUseCase";
import { VerifyLoginChallengeUseCase } from "../application/VerifyLoginChallengeUseCase";
import { CheckSessionUseCase } from "../application/CheckSessionUseCase";
import { RegisterDeviceChallengeUseCase } from "../application/RegisterDeviceChallengeUseCase";
import { VerifyRegisterDeviceUseCase } from "../application/VerifyRegisterDeviceUseCase";
import { DeleteDeviceUseCase } from "../application/DeleteDeviceUseCase";
import { UpdatePasswordUseCase } from "../application/UpdatePasswordUseCase";
import { UpdateEmailUseCase } from "../application/UpdateEmailUseCase";
import { GetSecurityProfileUseCase } from "../application/GetSecurityProfileUseCase";
export const authRepository = new PrismaAuthRepository();
export const tokenService = new JoseTokenService();
export const loginWithPasswordUseCase = new LoginWithPasswordUseCase(authRepository);
export const generateLoginChallengeUseCase = new GenerateLoginChallengeUseCase(authRepository);
export const verifyLoginChallengeUseCase = new VerifyLoginChallengeUseCase(authRepository);
export const checkSessionUseCase = new CheckSessionUseCase(authRepository, tokenService);
export const registerDeviceChallengeUseCase = new RegisterDeviceChallengeUseCase(authRepository, tokenService);
export const verifyRegisterDeviceUseCase = new VerifyRegisterDeviceUseCase(authRepository, tokenService);
export const deleteDeviceUseCase = new DeleteDeviceUseCase(authRepository, tokenService);
export const updatePasswordUseCase = new UpdatePasswordUseCase(authRepository, tokenService);
export const updateEmailUseCase = new UpdateEmailUseCase(authRepository, tokenService);
export const getSecurityProfileUseCase = new GetSecurityProfileUseCase(authRepository, tokenService);